package com.atlassian.cpji.fields.custom;

import com.atlassian.cpji.fields.CustomFieldMappingResult;
import com.atlassian.cpji.fields.MappingResult;
import com.atlassian.cpji.rest.model.CustomFieldBean;
import com.atlassian.jira.issue.Issue;
import com.atlassian.jira.issue.IssueInputParameters;
import com.atlassian.jira.issue.fields.CustomField;
import com.atlassian.jira.issue.issuetype.IssueType;
import com.atlassian.jira.project.Project;
import com.google.common.collect.Lists;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

/**
 * Abstract class for mapping custom fields which contain a single value.
 *
 * @param <T> the type of value stored by the custom field
 * @since v2.1
 */
public abstract class AbstractSingleValueCFMapper<T> implements CustomFieldMapper
{
    /**
     * Convert the value stored by the custom field to a String. The value will not be null.
     *
     * @param value the value given by the custom field, see {@link CustomField#getValue(com.atlassian.jira.issue.Issue)}
     * @return a String representing the value
     */
    protected abstract String convertToString(T value);

    /**
     * Format the String value for the generated by {@link #convertToString(Object)}. The given String will have been
     * generated on the source JIRA instance. On the destination instance, we may need to format the value differently,
     * e.g. if the value is a Date, each JIRA instance may have a different format for representing dates as strings.
     *
     * @param value a String representing the custom field value
     * @return a formatted String recognisable by the current JIRA instance
     */
    protected abstract String formatString(String value);

    /**
     * Determines if the given value is value for the given custom field. The value will not be null.
     * 
     * @param value the custom field value, will not be null
     * @param customField
     * @param project
     * @param issueType
     * @return true if the value is valid, false if otherwise
     */
    protected abstract boolean isValidValue(String value, CustomField customField, Project project, IssueType issueType);

    @Override
    public CustomFieldBean createFieldBean(final CustomField customField, final Issue issue)
    {
        final Object value = customField.getValue(issue);
        List<String> values;

        if (value != null)
        {
            try
            {
                final String stringValue = convertToString((T) value);
                values = Lists.newArrayList(stringValue);
            }
            catch (final ClassCastException e)
            {
                // Value is unrecognised type, ignore it
                values = Collections.emptyList();
            }
        }
        else
        {
            // Value is null, ignore it
            values = Collections.emptyList();
        }

        final String customFieldType = customField.getCustomFieldType().getClass().getCanonicalName();
        return new CustomFieldBean(customFieldType, customField.getName(), customField.getId(), values);
    }

    @Override
    public CustomFieldMappingResult getMappingResult(final CustomFieldBean customFieldBean, final CustomField customField, final Project project, final IssueType issueType)
    {
        final List<String> validValues;
        final List<String> invalidValues;

        final String value = getValue(customFieldBean.getValues());
        if (value == null)
        {
            validValues = Collections.emptyList();
            invalidValues = Collections.emptyList();
        }
        else if (isValidValue(value, customField, project, issueType))
        {
            validValues = Arrays.asList(value);
            invalidValues = Collections.emptyList();
        }
        else
        {
            validValues = Collections.emptyList();
            invalidValues = Arrays.asList(value);
        }

        return new CustomFieldMappingResult(validValues, invalidValues);
    }

    @Override
    public void populateInputParameters(final IssueInputParameters inputParameters, final CustomFieldMappingResult mappingResult, final CustomField customField, final Project project, final IssueType issueType)
    {
        final String value = getValue(mappingResult.getValidValues());
        if (value != null)
        {
            final String formattedValue = formatString(value);
            inputParameters.addCustomFieldValue(customField.getId(), formattedValue);
        }
    }

    private String getValue(final List<String> values)
    {
        if (values == null || values.isEmpty())
        {
            return null;
        }

        return values.get(0);
    }
}
